### ISSUE TITLE
Custom MAC address for each session?

### ISSUE THREAD

**Issue by minhng99** [paulusmack/ppp#112]
Hi, I want to run multiple PPPoE session on my machine but it require different MAC address, since I can only set the MAC address for the physical interface and not the one that ppp has created, I wonder if you could add a function for set custom MAC address for the session so I could use multiple PPPoE account on a single machine at the same time?

**Comment by paulusmack** [comment]
There is already a "pppoe-mac" option which should do what you want, assuming that you're talking about being a client of several different PPPoE servers. If you want your machine to act as multiple PPPoE servers, that's outside the scope of pppd since the rp-pppoe plugin doesn't have the ability to act as a PPPoE server.
