### ISSUE TITLE
pppd password visible in `ps` (and the Processes screen of LuCI webui)

### ISSUE THREAD

**Issue by giro83** [paulusmack/ppp#134]
OpenWrt 19.07 on Linksys WRT3200ACM

Originally reported here (incorrectly): https://bugs.openwrt.org/index.php?do=details&task_id=2727

When configuring the WAN interface to use PPPoE and supplying a username/password, these are visible as arguments in `ps` output from the cli (and in the Processes screen of the LuCI webui).

There are tools (e.g. curl, IIRC) that successfully hide sensitive arguments from /proc/PID/cmdline. Perhaps pppd could be enhanced to do this.

<img width="1070" alt="Screenshot 2020-01-12 at 00 40 31" src="https://user-images.githubusercontent.com/20286572/72564055-dce5dd80-38a6-11ea-985a-820a499c34bd.png">

**Comment by paulusmack** [comment]
I just committed a change to fix this, BUT --- it remains a bad idea to put the password on the command line, because there is inevitably a short time window after starting the process before it gets to processing and overwriting that argument. It is a much better idea to put the password in a secrets file (/etc/ppp/pap-secrets, etc.) or use the +ua option, which reads both username and password from the file given as the argument.
