### ISSUE TITLE
Address clashes between pppd and existing routes.

### ISSUE THREAD

**Issue by dexdyne** [paulusmack/ppp#46]
I'm sorry to say this is about an ancient version of pppd, 2.4.3, but that's what's on the box.

If I have an eth0 set up as 192.168.1.123 mask 255.255.0.0.

( Sorry this is an end-user config, and they were clearly only thinking about their own local networking needs, not the GPRS link I might want to add. )

Then I start up a GPRS session.

I found the GPRS link has configured itself as 192.168.111.1 - clearly not a happy situation.

Now I see on the web that if I omit both auth and noauth options, then the negotiation ought to avoid clashing address ranges. Something didn't work as well as documented.

It is just about possible that the default route via eth0 has been taken down before the negotiation happens, but I don't think that is the case.

Is there anything obvious I can do ( apart from trying to retro-fit the latest pppd )

**Comment by dexdyne** [comment]
OK - I find I take the eth0-related default route down in the ip-pre-up script, so pppd can set a default gateway. Is that my cause?

**Comment by paulusmack** [comment]
In general pppd doesn't have any logic to choose IP addresses based on what other network devices the system has. It either takes what the other end tells it, or it tells the other end what addresses to use based on command-line options.

Closing this because it is stale and the issue is not something that can be solved in pppd.
