### ISSUE TITLE
Async Control Character Map and PPTP

### ISSUE THREAD

**Issue by aaron-w2** [paulusmack/ppp#84]
It seems that no matter what I do I am seeing pppd request the async control character map of 0x00000000 during LCP negotiation with my router during PPTP setup. The router rejects the async control character map parameter and there is no way to remove this from the negotiation it seems. This is connecting using ppp 2.4.7 to my Mikrotik router.

I have a pcap with this failure from wireshark.

**Comment by aaron-w2** [comment]
[pptp-fail.pcapng.zip](https://github.com/paulusmack/ppp/files/1065793/pptp-fail.pcapng.zip)

**Comment by paulusmack** [comment]
It seems like your pppd isn't receiving any packets from the router, since all it is doing is sending out its own configure-request over and over. If your pppd was seeing the configure-reject from the peer it would resend its configure-request without the asyncmap, accomp or pcomp options. You could use the 'debug' option on your end (e.g. add it to /etc/ppp/options) to see what packets pppd on your end is seeing from the router. If it's not seeing any of the packets from the router then you will need to debug that.

**Comment by aaronw2** [comment]
I found the problem. It seems that SuSEfirewall2 blocks GRE by default. I had to do a lot of hunting to figure out how to permit it but now it's working.
